### ISSUE TITLE
Readme doesn't mention that you need to set :hooks

### ISSUE THREAD

**Issue by tom-pang** [brentonashworth/lein-difftest#1]
In lein's project file, you have to set :hooks to actually load hooks (see lein's documentation). I can't actually seem to get difftest working at all on clojure 1.2, even with :hooks set.

**Comment by brentonashworth** [comment]
I have updated the README. Note that you only have to add :hooks if you are using Leiningen 1.3. A new version of lein-difftest is in Clojars (1.3.0) that will work with Clojure 1.2.

Thank you for the feedback. Let me know if you have any other problems.

Brenton

**Comment by tom-pang** [comment]
Just to confirm that all works now. Have you considered writing something like junit max's test running algorithm for diffview? Basically instead of running all the tests in whatever order they are in a file, keep track of which tests run the longest, and which ones recently broke, then prioritize broken tests, and then shorter running tests over longer running tests.

**Comment by brentonashworth** [comment]
This plugin is very simple and will most likely stay that way. It simply modifies some of the reporting functions of clojure.test to produce alternate output.

I have thought of something along these lines for deview. Not specifically what you mention here. My thought was to figure out the dependency structure for a project and then based on the changes that have been made to source files, figure out which tests will need to be re-run. I have only had the idea and not thought too deeply about this so it may be very difficult to do. I will also think about what you mentioned here. Thank you for reporting this problem and for the idea.

**Comment by tom-pang** [comment]
I might be able to do something like this for deview (I'm not sure that it works with clojure 1.2 though). I'll give you a shout when I've looked into it.

**Comment by brentonashworth** [comment]
I have done a lot of work on deview in the watch branch. This branch does work with 1.2 and works in conjunction with the watch branch of the server in the lein-deview project. If you would like to try out the changes then you would add [deview/lein-deview "1.2.0-SNAPSHOT"] to your project, run "lein deview &" and finally run the deview watch branch in the usual way.  The new version is more tightly integrated with lein using it to run tests in a new process. It will "watch" your project for changes and then run tests automatically when any file is saved. It also will send growl notifications. Currently it is a little slow because it runs each namespace in a new process. I am working on that.

If you make any changes to deview then make sure to start with the watch branch or wait until I merge those changes into master.

If you do attempt this, which would be great, then let me know if you have any questions.
